name: Docker Image CI - build app and dockerize it

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out that repo
      - uses: actions/checkout@v2
      # Set OpenJDK 16
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' 
          # See 'Supported distributions' for available options - https://adoptopenjdk.net/
          java-version: 16
      # Build whole app with mven
      - name: Build with Maven
        run: mvn -B install package --file pom.xml
      # - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dukes-hidden-stash:$(date +%s)
      # Print the pretty message to DevOps
      - name: ASCII Art Action
        # - uses: mscoutermarsh/ascii-art-action@5bc07de66916de6d91223177c49abd531fb1a6e5
        uses: mscoutermarsh/ascii-art-action@1.0.1
        with:
        # Text to print with asciify
          text: DONE, ship it.
